### ISSUE TITLE
request: in the right sidebar, prioritize linebreaks at `.`

### ISSUE THREAD

**Issue by hrmacbeth** [leanprover/doc-gen4#100]
In doc-gen3, the path of the file currently displayed appears at the top of the right sidebar, with linebreaks preferentially inserted at the `.` between a folder and its subfolder.  In doc-gen4 the linebreaks simply fall where they may, which is a small loss in readability.  Could the doc-gen3 behaviour be implemented here?

Compare, e.g.,
https://leanprover-community.github.io/mathlib_docs/algebra/group_power/basic.html
https://leanprover-community.github.io/mathlib4_docs/Mathlib/Algebra/GroupPower/Basic.html

**Comment by hargoniX** [comment]
This is most likely a CSS thing I guess? A quick comparision between the CSS attributes of the two things does not show an obvious difference for me though. If someone can tell me how you did it I'll be happy to add it. As so often I sadly have to say I'm not a frontend developer, I don't know how to do this :(

**Comment by hrmacbeth** [comment]
Fixed by #115
