### ISSUE TITLE
Linkifier to special characters

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/doc-gen4#114]
The linkifier doesn't work well when linking to names with special characters, including primes

Examples:
https://leanprover-community.github.io/mathlib4_docs/find/?pattern=MonoidHom.compl₂#doc
https://leanprover-community.github.io/mathlib4_docs/find/?pattern=pow_succ'#doc

**Comment by hargoniX** [comment]
This is because the parameter is URL encoded, the fix should be pretty easy in theory (just decode the URL) but something else is not working for me right now.
