### ISSUE TITLE
Mangled docstring for `CoeHTCT`

### ISSUE THREAD

**Issue by eric-wieser** [leanprover/doc-gen4#123]
I'm not sure what's going on here. [The docs](https://leanprover-community.github.io/mathlib4_docs/Init/Coe.html#CoeHTCT) say

> Coerces a value of type `α` to type `β`. Accessible by the notation `↑x↑x`, or by double type ascription `((x : α) : β)`.

but the source says
```lean
  /-- Coerces a value of type `α` to type `β`. Accessible by the notation `↑x`,
  or by double type ascription `((x : α) : β)`. -/
```

Somehow `↑x` ended up duplicated.

**Comment by eric-wieser** [comment]
The docstring for https://leanprover-community.github.io/mathlib4_docs/Lean/Meta/Eqns.html#Lean.Meta.GetUnfoldEqnFn is even worse, it says
```
(xs : Nat) →
  f xs =
    match xs with
    | [] => []
    | x::xs => (x+1)::f xs
→
  f xs =
    match xs with
    | [] => []
    | x::xs => (x+1)::f xs
```
but the source says
```
(xs : Nat) →
  f xs =
    match xs with
    | [] => []
    | x::xs => (x+1)::f xs
```

**Comment by semorrison** [comment]
Further examples at https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/.E2.89.A4.2C.20.E2.89.A5.2C.20and.20.E2.88.88.20symbols.20are.20duplicated.20in.20docs4.
