### ISSUE TITLE
Mangled docstring for `congrArg`

### ISSUE THREAD

**Issue by chabulhwi** [leanprover/doc-gen4#126]
[Source][1]: 
> This is more powerful than it might look at first, because you can also use a lambda expression for `f` to prove that `<something containing a₁> = <something containing a₂>`.

[Docs][2]:
> This is more powerful than it might look at first, because you can also use a lambda expression for `f` to prove that `= `.

Zulip discussion: https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/mangled.20docstring.20for.20docs4.23congrArg

[1]: https://github.com/leanprover/lean4/blob/742d053a97bdd109a41a921facd1cd6a55e89bc7/src/Init/Prelude.lean#L341-L343
[2]: https://leanprover-community.github.io/mathlib4_docs/Init/Prelude.html#congrArg

**Comment by eric-wieser** [comment]
Note if you view the source, `<something containing a₁>` is being output unescaped. I'm pretty sure that interpreting `<html>` inside `` ` ``-code is not conformant markdown behavior.

**Comment by acmepjz** [comment]
I think this is already fixed and we can close it? (but we need to ensure that #189 does not break it again)
