### ISSUE TITLE
@[reducible] attributes are not shown

### ISSUE THREAD

**Issue by alreadydone** [leanprover/doc-gen4#144]
For example, the @[inline] attribute on [Function.dcomp](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Init/Function.html#Function.dcomp) is shown but @[reducible] is not. On the other hand [`abbrev`](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Condensed/Abelian.html#CondensedAb)s are properly distinguished from `def`s.

**Comment by hargoniX** [comment]
Fixed locally:
![image](https://github.com/leanprover/doc-gen4/assets/33270164/87de6227-34bf-4283-9f04-4635f6601c77)
coming to mathlib4_docs next build cycle.
