### ISSUE TITLE
Put inductive/structure documentation before field documentation

### ISSUE THREAD

**Issue by nomeata** [leanprover/doc-gen4#161]
Consider a user trying to find out what `Std.Format` is. They navigate to 

https://leanprover-community.github.io/mathlib4_docs/Init/Data/Format/Basic.html#Std.Format

and the first thing they read is that `.nil` is “The empty format”. Only a good page further down, and separated from the last constructor’s doc with only an easy-to-miss change of indentation and font size, they find

> A string with pretty-printing information for rendering in a column-width-aware way.
> 
> The pretty-printing algorithm is based on Wadler's paper [A Prettier Printer](https://homepages.inf.ed.ac.uk/wadler/papers/prettier/prettier.pdf).

Would it be possible to put the main documentation for the structure/inductive _before_ the fields? See maybe the [Haskell docs](https://hackage.haskell.org/package/base-4.19.0.0/docs/Prelude.html#t:Foldable) for inspiration.

**Comment by hargoniX** [comment]
Funnily enough this was the original behavior and people on the Zulip explicitly requested me to do the change to how it is now. See commit d3d67c1d927663e64d40c1bf6413ece72a2ba9a5 and e5ff71991d8102b9711211a6d8e8880534100e41. So if you want this to be changed I guess you'll have to arrange yourself with @eric-wieser^^

**Comment by hargoniX** [comment]
Originally we used to have the ctor documentation above the ctor type but that was changed by @eric-wieser. If we do this change of swapping the whole type docs above the thing, would it be sensible to also reswap the ctor doc? And what do you, Eric, think about switching the type doc above given that you originally advocated for the ctor doc switch?

**Comment by eric-wieser** [comment]
I still firmly believe that constructors and fields *names* should be shown *before* their descriptions. I don't think I ever expressed an opinion on where the main docstring belongs, beside it appearing somewhere after the name.

**Comment by nomeata** [comment]
So inductive name, type, docs, followed by list of ctor, type, docs makes sense, does it?
