### ISSUE TITLE
De-indent comment block

### ISSUE THREAD

**Issue by nomeata** [leanprover/doc-gen4#165]
Browsing [the documentation](https://leanprover-community.github.io/mathlib4_docs/Lean/Expr.html#Lean.Expr) I was a bit confused why some paragraphs are randomly indendet, e.g. “The [bvar](https://leanprover-community.github.io/mathlib4_docs/Lean/Expr.html#Lean.Expr.bvar) constructor…”.

My theory is that it’s because the whole doc string block is indented in the source code:
```

/--
Lean expressions. This data structure is used in the kernel and
elaborator. However, expressions sent to the kernel should not
contain metavariables.

Remark: we use the `E` suffix (short for `Expr`) to avoid collision with keywords.
We considered using «...», but it is too inconvenient to use.
-/
inductive Expr where
  /--
  The `bvar` constructor represents bound variables, i.e. occurrences
  of a variable in the expression where there is a variable binder
  above it (i.e. introduced by a `lam`, `forallE`, or `letE`).
  …
  -/
  | bvar (deBruijnIndex : Nat)
```

Looking at this, I doubt that the author wanted to have the markdown interpreted as indented.

If that analysis is correct, maybe the tool should de-indent by all common whitespace?

Probably also for
```
/--
  This style, which I have seen too.
-/
def foo := …
```

I might be barking on the wrong hill, though.

**Comment by hargoniX** [comment]
With respect to docstring rendering I'm currently hoping that David's new doc tooling will give some clear semantics to docstrings at last that the doc-gen renderer can then just stick to. Hence I'd suggest to hold our breaths for the first release of that.

**Comment by nomeata** [comment]
Fair enough, and the issue isn't servere.

**Comment by acmepjz** [comment]
I think this is a CSS problem...

**Comment by eric-wieser** [comment]
Here's another issue; https://leanprover-community.github.io/mathlib4_docs//Init/Data/Format/Basic.html#Std.Format has in its source:
````
  /-- `align` tells the formatter to pad with spaces to the current indent,
  or else add a newline if we are already at or past the indent. For example:
  ```
  nest 2 <| "." ++ align ++ "a" ++ line ++ "b"
  ```
  results in:
  ```
  . a
    b
  ```
  If `force` is true, then it will pad to the indent even if it is in a flattened group.
  -/
  | align (force : Bool) : Format
````
but this renders as

>   results in:
>   ```
>   . a
>   b
>   ```

which of course fails to capture the behavior at all.
