### ISSUE TITLE
Implement the required endpoints for src#

### ISSUE THREAD

**Issue by hargoniX** [leanprover/doc-gen4#30]
https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/.E2.9C.94.20docs4.23/near/271780657

**Comment by hargoniX** [comment]
The general find# and src# system also needs to be reworked, this is because we generate a directory for every declaration but some declarations contain characters like `?` which Windows doesn't allow in file/dir names :/. So in order to get Windows support we need to implement the find# and src# functionality fully in JS.

**Comment by gebner** [comment]
It's not just Windows, also on Linux there are restrictions on file names (depending on the file system, on ext4 a filename may not be longer than 255 characters).

**Comment by hargoniX** [comment]
I think at the point where a Lean declaration gets longer than 255 characters together with its namespaces the user probably deserves doc-gen to fail :P

**Comment by gebner** [comment]
I've tried to run doc-gen4 on mathport and ran into that issue with some autogenerated declaration.  The new instance names (`instA...`) are also humongous, I wouldn't be surprised if they end up being longer than 255 characters in some cases.

**Comment by hargoniX** [comment]
Hmmm...well with the new approach of @xubaiw in #38 we should get rid of this subdirectory stuff in favour of just one endpoint with some JS running anyways so hopefully that won't be an issue anymore.
