### ISSUE TITLE
Fix all the broken links in the navbar tree

### ISSUE THREAD

**Issue by hargoniX** [leanprover/doc-gen4#37]
With the current navbar tree generation lots of links are actually broken/don't exist. The navbar names that do not actually point to real files should not be marked with a link to those files.

**Comment by xubaiw** [comment]
One approach can be to flatten the module hierarchy, e.g.

- Mathlib
    - Mathlib.Algebra
        - Mathlib.Algebra.Group
            - Mathlib.Algebra.Group.Basic
            - Mathlib.Algebra.Group.Defs
        - Mathlib.Algebra.Ring
            - MAthlib.Algebra.Ring.Basic

into

- Mathlib
    - Mathlib.Algebra.Group.Basic
    - Mathlib.Algebra.Group.Defs
    - MAthlib.Algebra.Ring.Basic

which reflects the actual parent-children relation between modules.

**Comment by gebner** [comment]
I don't think that flattening is a good idea mathlib, we've got ~2000 modules.

**Comment by gebner** [comment]
I've also noticed two other regressions:
1. The module names no longer fit in the sidebar (which is an issue now that the full names are shown):
![modulenameoverflow](https://user-images.githubusercontent.com/313929/155185349-f6a8bfe4-cf83-49fc-a3e4-db0c123dc527.png)
2. The navbar used to remember the position when navigating to another page (i.e., on loading it scrolls down to the current file).  This doesn't work for me anymore.
