### ISSUE TITLE
Generate error when lean toolchain mismatches?

### ISSUE THREAD

**Issue by bollu** [leanprover/doc-gen4#40]
Currently, `doc-gen4` segfaults when run an older Lean toolchain. Is it possible to detect this case and show a user-facing error?

**Comment by hargoniX** [comment]
This might be something I'll be able to resolve while implementing #6 fully since this requires further integration with Lake which is also how the build process is managed.

**Comment by hargoniX** [comment]
This will be just a warning not a hard error since it will only segfault if there are sufficient API differences between versions.
