### ISSUE TITLE
LeanInk: Pretty rendering

### ISSUE THREAD

**Issue by hargoniX** [leanprover/doc-gen4#61]
Alectryon can render pretty versions of data structures like rbtrees,
integrating this feature from the compiler: https://github.com/leanprover/lean4/pull/1238
might allow us to do the same (https://alectryon-paper.github.io/snippets/rbt.html)

**Comment by EdAyers** [comment]
yes this is exactly a use case of the user-widgets feature

**Comment by hargoniX** [comment]
Won't implement, we have Verso.
