### ISSUE TITLE
Request: In library directory sidebar, do not repeat the full address of files

### ISSUE THREAD

**Issue by hrmacbeth** [leanprover/doc-gen4#95]
See discussion on Zulip [here](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/mathlib4.20docs.20suggestions) (point 2) and [here](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Online.20docs).  This makes it easier to browse deeply nested file trees (as is common in mathlib); it was the docs3 behaviour.

**Comment by winstonyin** [comment]
Replacing `module.toString` by `module.getString!` may do the trick

**Comment by hargoniX** [comment]
Got it implemented now. Should deploy to mathlib4_docs soon :tm:.

Also you people need to slow down with the port, there is so much new stuff building the docs on my laptop is already going in the 10s of minutes and 2 digit GB of RAM for me :stuck_out_tongue_winking_eye:

**Comment by hrmacbeth** [comment]
Thank you!!
